---
title: "p8105_hw2_kl3181"
author: Kelley Lou
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```

## Problem 1
Read in Mr. Trashweel data set.
```{r import_trashwheel}
trashwheel_df = read_xlsx(
  "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
      sheet = "Mr. Trash Wheel",
      range = cell_cols("A:N")) %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>% 
  mutate(
      sports_balls = round(sports_balls),
      sports_balls = as.integer(sports_balls)
  )
```

Read in precipitation data for 2018 and 2017. 
```{r}
precip_2018 = read_excel(
  "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
      sheet = "2018 Precipitation", 
      skip = 1
      ) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate(year)

precip_2017 = read_excel(
  "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
      sheet = "2017 Precipitation",
      skip = 1
      ) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate(year)
```


